/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import connection.MySQL;
import entity.Fmt;
import entity.Funcionario;
import javax.swing.JOptionPane;

/**
 *
 * @author gusta
 */
public class ViewConsultaCliente extends javax.swing.JFrame {
    MySQL mysqldb = new MySQL();
    Fmt format = new Fmt();
    
    /**
     * Creates new form ViewConsultaCliente
     */
    public ViewConsultaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNameFuncionario1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmailFuncionario1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCidade1 = new javax.swing.JTextField();
        cbEstado1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLogradouro1 = new javax.swing.JTextArea();
        btnAtualiza1 = new javax.swing.JButton();
        nr_cep = new javax.swing.JFormattedTextField();
        btnVolta1 = new javax.swing.JButton();
        btnExclui1 = new javax.swing.JButton();
        nr_cpf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnBusca1 = new javax.swing.JButton();
        btnLimpa1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta Cliente"));

        jLabel3.setText("Nome:");

        jLabel4.setText("E-mail:");

        jLabel11.setText("Cidade:");

        cbEstado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel12.setText("Estado:");

        jLabel13.setText("CEP:");

        jLabel14.setText("Logradouro:");

        txtLogradouro1.setColumns(20);
        txtLogradouro1.setRows(5);
        jScrollPane2.setViewportView(txtLogradouro1);

        btnAtualiza1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updated.png"))); // NOI18N
        btnAtualiza1.setText("Atualizar");
        btnAtualiza1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualiza1btnCadastra(evt);
            }
        });

        try {
            nr_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnVolta1.setText("Voltar");
        btnVolta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolta1ActionPerformed(evt);
            }
        });

        btnExclui1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/limpar-limpo.png"))); // NOI18N
        btnExclui1.setText("Excluir");
        btnExclui1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExclui1ActionPerformed(evt);
            }
        });

        jLabel16.setText("CPF:");

        btnBusca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/binoculars.png"))); // NOI18N
        btnBusca1.setText("Buscar");
        btnBusca1.setToolTipText("");
        btnBusca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusca1ActionPerformed(evt);
            }
        });

        btnLimpa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/limpar-limpo.png"))); // NOI18N
        btnLimpa1.setText("Limpar");
        btnLimpa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(211, 211, 211)
                                .addComponent(jLabel3))
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nr_cpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(txtEmailFuncionario1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameFuncionario1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnBusca1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAtualiza1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExclui1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                    .addComponent(btnVolta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nr_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCidade1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(cbEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nr_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusca1)
                    .addComponent(btnLimpa1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbEstado1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nr_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCidade1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualiza1)
                    .addComponent(btnExclui1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolta1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpa1ActionPerformed
        limpaForm();
    }//GEN-LAST:event_btnLimpa1ActionPerformed

    private void btnBusca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusca1ActionPerformed
        mysqldb.conectaBanco();

        Funcionario novo_funcionario = new Funcionario();

        try {
            if (docCliente.getText().isBlank()) {
                JOptionPane.showMessageDialog(rootPane, "O campo DOCUMENTO não pode ser vazio para realizar a busca");
            } else {
                String query
                = "select * "
                + "from cad_funcionario "
                + "where nr_cpf_cnpj = '" + docCliente.getText()+"'";
                System.out.println(query);
                this.mysqldb.executarSQL(query);

                while (this.mysqldb.getResultSet().next()) {
                    novo_funcionario.setTpFj(this.mysqldb.getResultSet().getString(2));
                    novo_funcionario.setNrCpfCnpj(this.mysqldb.getResultSet().getString(3));
                    novo_funcionario.setNmCliente(this.mysqldb.getResultSet().getString(4));

                    novo_funcionario.setFgAtivo(Integer.parseInt(this.mysqldb.getResultSet().getString(5)));

                    novo_funcionario.setNmEmail(this.mysqldb.getResultSet().getString(6));
                    novo_funcionario.setNrCep(this.mysqldb.getResultSet().getString(7));
                    novo_funcionario.setDsEndereco(this.mysqldb.getResultSet().getString(8));
                    novo_funcionario.setSgEstado(this.mysqldb.getResultSet().getString(9));
                    novo_funcionario.setNmMunicipio(this.mysqldb.getResultSet().getString(10));
                }

                if (!novo_funcionario.getNrCpfCnpj().isEmpty()) {

                    txtNameFuncionario.setText(novo_funcionario.getNmCliente());
                    txtEmailFuncionario.setText(novo_funcionario.getNmEmail());
                    txtCidade.setText(novo_funcionario.getNmMunicipio());
                    txtCep.setText(novo_funcionario.getNrCep());
                    txtLogradouro.setText(novo_funcionario.getDsEndereco());
                    cbEstado.setSelectedItem(novo_funcionario.getSgEstado());

                    if (novo_funcionario.getFgAtivo()== 1) {
                        cbFgAtivo.setSelectedItem("Sim");
                    } else {
                        cbFgAtivo.setSelectedItem("Não");
                    }

                    docCliente.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "O funcionário procurado não existe na base de dados.");
                }

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERRO: Usuário não encontrado");
        }
        finally{
            mysqldb.fechaBanco();
        }
    }//GEN-LAST:event_btnBusca1ActionPerformed

    private void btnExclui1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExclui1ActionPerformed
        mysqldb.conectaBanco();
        boolean status = false;

        try {
            if (docCliente.getText().isBlank()) {
                JOptionPane.showMessageDialog(rootPane, "O campo DOCUMENTO não pode ser vazio para realizar a exclusão");
            }
            else {
                String query = "DELETE FROM cad_funcionario WHERE nr_cpf_cnpj = '" + docCliente.getText() + "'";

                status = this.mysqldb.updateSQL(query);

                if (status) {
                    JOptionPane.showMessageDialog(rootPane, "Funcionário excluído com sucesso!");
                    limpaForm();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Funcionário não pôde ser excluído");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        } finally {
            mysqldb.fechaBanco();
        }
    }//GEN-LAST:event_btnExclui1ActionPerformed

    private void btnVolta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolta1ActionPerformed
        ViewSystemMain getViewSystemMain = new ViewSystemMain();

        this.setVisible(false);

        getViewSystemMain.setVisible(true);
    }//GEN-LAST:event_btnVolta1ActionPerformed

    private void btnAtualiza1btnCadastra(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualiza1btnCadastra
        try {
            mysqldb.conectaBanco();

            Funcionario funcionario = new Funcionario();

            funcionario.setNrCpfCnpj(format.NrDb(docCliente.getText()));
            funcionario.setNmCliente(txtNameFuncionario.getText());

            if (cbFgAtivo.getSelectedItem().equals("Sim")) {
                funcionario.setFgAtivo(1);
            } else {
                funcionario.setFgAtivo(0);
            }

            funcionario.setNmEmail(txtEmailFuncionario.getText());
            funcionario.setNrCep(format.NrDb(txtCep.getText()));
            funcionario.setDsEndereco(txtLogradouro.getText());
            funcionario.setSgEstado((String)cbEstado.getSelectedItem());
            funcionario.setNmMunicipio(txtCidade.getText());

            String query =
            "UPDATE cad_funcionario set "
            +"nr_cpf_cnpj = '" + funcionario.getNrCpfCnpj()  + "',"
            +"nm_cliente  = '" + funcionario.getNmCliente()  + "',"
            +"fg_ativo    =  " + funcionario.getFgAtivo()    + ","
            +"nm_email    = '" + funcionario.getNmEmail()    + "',"
            +"nr_cep      = '" + funcionario.getNrCep()      + "',"
            +"ds_endereco = '" + funcionario.getDsEndereco() + "',"
            +"sg_estado   = '" + funcionario.getSgEstado()   + "',"
            +"nm_municipio= '" + funcionario.getNmMunicipio()+ "' "
            +"WHERE nr_cpf_cnpj = '" + funcionario.getNrCpfCnpj() + "'";

            int status = 0;

            status = this.mysqldb.insertSQL(query);

            if (status == 1) {
                JOptionPane.showMessageDialog(rootPane, "Funcionário atualizado com sucesso!");
                limpaForm();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Houve problemas na atualização do funcionário. Revise os dados.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "ERRO: Não foi possível atualizar o registro.");
        } finally {
            mysqldb.fechaBanco();
        }
    }//GEN-LAST:event_btnAtualiza1btnCadastra

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewConsultaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualiza;
    private javax.swing.JButton btnAtualiza1;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnBusca1;
    private javax.swing.JButton btnExclui;
    private javax.swing.JButton btnExclui1;
    private javax.swing.JButton btnLimpa;
    private javax.swing.JButton btnLimpa1;
    private javax.swing.JButton btnVolta;
    private javax.swing.JButton btnVolta1;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbEstado1;
    private javax.swing.JComboBox<String> cbFgAtivo;
    private javax.swing.JTextField docCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFormattedTextField nr_cep;
    private javax.swing.JTextField nr_cpf;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCidade1;
    private javax.swing.JTextField txtEmailFuncionario;
    private javax.swing.JTextField txtEmailFuncionario1;
    private javax.swing.JTextArea txtLogradouro;
    private javax.swing.JTextArea txtLogradouro1;
    private javax.swing.JTextField txtNameFuncionario;
    private javax.swing.JTextField txtNameFuncionario1;
    // End of variables declaration//GEN-END:variables

    private void limpaForm() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
