/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import connection.MySQL;
import entity.Fmt;
import entity.Funcionario;
import javax.swing.JOptionPane;
import model.TDBComboBox;

/**
 *
 * @author Felipe Lima
 */
public class ViewConsultaFuncionario extends javax.swing.JFrame {
    MySQL mysqldb = new MySQL();
    Fmt format = new Fmt();
    
    /**
     * Creates new form ViewConsultaFuncionario
     */
    public ViewConsultaFuncionario() {
        initComponents();
        TDBComboBox cbos = new TDBComboBox();
        
        cbos.setStatus(cbMunicipio, "localidade_municipio", "nm_municipio", null);
        cbos.setStatus(cbEstado, "localidade_estado", "sg_estado", null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNameFuncionario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmailFuncionario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLogradouro = new javax.swing.JTextArea();
        btnAtualiza = new javax.swing.JButton();
        cbFgAtivo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        btnVolta = new javax.swing.JButton();
        btnExclui = new javax.swing.JButton();
        docCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnBusca = new javax.swing.JButton();
        btnLimpa = new javax.swing.JButton();
        cbMunicipio = new javax.swing.JComboBox<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta Funcionário"));

        jLabel1.setText("Nome:");

        jLabel2.setText("E-mail:");

        jLabel5.setText("Cidade:");

        jLabel6.setText("Estado:");

        jLabel7.setText("CEP:");

        jLabel8.setText("Logradouro:");

        txtLogradouro.setColumns(20);
        txtLogradouro.setRows(5);
        jScrollPane1.setViewportView(txtLogradouro);

        btnAtualiza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updated.png"))); // NOI18N
        btnAtualiza.setText("Atualizar");
        btnAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizabtnCadastra(evt);
            }
        });

        cbFgAtivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Sim", "Não" }));

        jLabel9.setText("Ativo:");

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnVolta.setText("Voltar");
        btnVolta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltaActionPerformed(evt);
            }
        });

        btnExclui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/limpar-limpo.png"))); // NOI18N
        btnExclui.setText("Excluir");
        btnExclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluiActionPerformed(evt);
            }
        });

        jLabel10.setText("Documento");

        btnBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/binoculars.png"))); // NOI18N
        btnBusca.setText("Buscar");
        btnBusca.setToolTipText("");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        btnLimpa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/limpar-limpo.png"))); // NOI18N
        btnLimpa.setText("Limpar");
        btnLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaActionPerformed(evt);
            }
        });

        cbMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMunicipioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEstado, 0, 199, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(docCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(txtEmailFuncionario, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameFuncionario)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(jLabel8)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnExclui, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                                .addComponent(btnVolta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(cbFgAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(300, 300, 300)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(211, 211, 211)
                                .addComponent(jLabel1))
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(docCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBusca)
                            .addComponent(btnLimpa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFgAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualiza)
                    .addComponent(btnExclui))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizabtnCadastra(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizabtnCadastra
        try {
            mysqldb.conectaBanco();

            Funcionario funcionario = new Funcionario();
            
            funcionario.setNrCpfCnpj(format.NrDb(docCliente.getText()));
            funcionario.setNmCliente(txtNameFuncionario.getText());

            if (cbFgAtivo.getSelectedItem().equals("Sim")) {
                funcionario.setFgAtivo(1);
            } else {
                funcionario.setFgAtivo(0);
            }

            funcionario.setNmEmail(txtEmailFuncionario.getText());
            funcionario.setNrCep(format.NrDb(txtCep.getText()));
            funcionario.setDsEndereco(txtLogradouro.getText());
            funcionario.setSgEstado((String)cbEstado.getSelectedItem());
            funcionario.setNmMunicipio((String)cbMunicipio.getSelectedItem());

            String query =
                     "UPDATE cad_funcionario set "
                    +"nr_cpf_cnpj = '" + funcionario.getNrCpfCnpj()  + "',"
                    +"nm_cliente  = '" + funcionario.getNmCliente()  + "',"
                    +"fg_ativo    =  " + funcionario.getFgAtivo()    + ","
                    +"nm_email    = '" + funcionario.getNmEmail()    + "',"
                    +"nr_cep      = '" + funcionario.getNrCep()      + "',"
                    +"ds_endereco = '" + funcionario.getDsEndereco() + "',"
                    +"sg_estado   = '" + funcionario.getSgEstado()   + "',"
                    +"nm_municipio= '" + funcionario.getNmMunicipio()+ "' "
                    +"WHERE nr_cpf_cnpj = '" + funcionario.getNrCpfCnpj() + "'";
            
            int status = 0;

            status = this.mysqldb.insertSQL(query);

            if (status == 1) {
                JOptionPane.showMessageDialog(rootPane, "Cliente atualizado com sucesso!");
                limpaForm();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Houve problemas na atualização do cliente. Revise os dados.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "ERRO: Não foi possível atualizar o registro.");
        } finally {
            mysqldb.fechaBanco();
        }
    }//GEN-LAST:event_btnAtualizabtnCadastra

    private void btnVoltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltaActionPerformed
        ViewSystemMain getViewSystemMain = new ViewSystemMain();

        this.setVisible(false);

        getViewSystemMain.setVisible(true);
    }//GEN-LAST:event_btnVoltaActionPerformed

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        mysqldb.conectaBanco();
        
        Funcionario novo_funcionario = new Funcionario();
        
        try {
            if (docCliente.getText().isBlank()) {
                JOptionPane.showMessageDialog(rootPane, "O campo DOCUMENTO não pode ser vazio para realizar a busca");
            } else {
                String query
                        = "select * "
                        + "from cad_funcionario "
                        + "where nr_cpf_cnpj = '" + docCliente.getText()+"'";
                System.out.println(query);
                this.mysqldb.executarSQL(query);

                while (this.mysqldb.getResultSet().next()) {
                    novo_funcionario.setTpFj(this.mysqldb.getResultSet().getString(2));
                    novo_funcionario.setNrCpfCnpj(this.mysqldb.getResultSet().getString(3));
                    novo_funcionario.setNmCliente(this.mysqldb.getResultSet().getString(4));
                    
                    novo_funcionario.setFgAtivo(Integer.parseInt(this.mysqldb.getResultSet().getString(5)));
                    
                    novo_funcionario.setNmEmail(this.mysqldb.getResultSet().getString(6));
                    novo_funcionario.setNrCep(this.mysqldb.getResultSet().getString(7));
                    novo_funcionario.setDsEndereco(this.mysqldb.getResultSet().getString(8));
                    novo_funcionario.setSgEstado(this.mysqldb.getResultSet().getString(9));
                    novo_funcionario.setNmMunicipio(this.mysqldb.getResultSet().getString(10));
                }

                if (!novo_funcionario.getNrCpfCnpj().isEmpty()) {
                    
                    txtNameFuncionario.setText(novo_funcionario.getNmCliente());
                    txtEmailFuncionario.setText(novo_funcionario.getNmEmail());
                    cbMunicipio.setSelectedItem(novo_funcionario.getNmMunicipio());
                    txtCep.setText(novo_funcionario.getNrCep());
                    txtLogradouro.setText(novo_funcionario.getDsEndereco());
                    cbEstado.setSelectedItem(novo_funcionario.getSgEstado());

                    if (novo_funcionario.getFgAtivo()== 1) {
                        cbFgAtivo.setSelectedItem("Sim");
                    } else {
                        cbFgAtivo.setSelectedItem("Não");
                    }

                    docCliente.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "O cliente procurado não existe na base de dados.");
                }

            }
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(rootPane, "ERRO: Cliente não encontrado"); 
        }
        finally{
            mysqldb.fechaBanco();
        }
           

    }//GEN-LAST:event_btnBuscaActionPerformed

    private void btnLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaActionPerformed
       limpaForm();
    }//GEN-LAST:event_btnLimpaActionPerformed

    private void btnExcluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluiActionPerformed
        mysqldb.conectaBanco();
        boolean status = false;
        
        try {
            if (docCliente.getText().isBlank()) {
                JOptionPane.showMessageDialog(rootPane, "O campo DOCUMENTO não pode ser vazio para realizar a exclusão");
            }
            else {
                String query = "DELETE FROM cad_funcionario WHERE nr_cpf_cnpj = '" + docCliente.getText() + "'";
                
                status = this.mysqldb.updateSQL(query);
                
                if (status) {
                    JOptionPane.showMessageDialog(rootPane, "Funcionário excluído com sucesso!");
                    limpaForm();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Funcionário não pôde ser excluído");
                }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        } finally {
            mysqldb.fechaBanco();
        }
    }//GEN-LAST:event_btnExcluiActionPerformed

    private void cbMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMunicipioActionPerformed

    public void limpaForm(){
       txtNameFuncionario.setText(null);
       txtEmailFuncionario.setText(null);
       txtCep.setText(null);
       txtLogradouro.setText(null);
       cbMunicipio.setSelectedIndex(0);
       cbEstado.setSelectedIndex(0);
       cbFgAtivo.setSelectedIndex(0);
       docCliente.setText(null);
       docCliente.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewConsultaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewConsultaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewConsultaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewConsultaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewConsultaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualiza;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnExclui;
    private javax.swing.JButton btnLimpa;
    private javax.swing.JButton btnVolta;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbFgAtivo;
    private javax.swing.JComboBox<String> cbMunicipio;
    private javax.swing.JTextField docCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtEmailFuncionario;
    private javax.swing.JTextArea txtLogradouro;
    private javax.swing.JTextField txtNameFuncionario;
    // End of variables declaration//GEN-END:variables
}
